In [3]:
import numpy as np #Import numpy as np in order to be easily called

# NORMALIZATION PROBLEM
### This problem involves the normalization of a set of values in a data set, which features centering, the subtraction of values from the mean, and scaling, the division of the centered values from the standard deviation

In [36]:
X = np.random.choice(100, size=(5,5)) #Create a random 5 by 5 array
print('Random Array: \n', X)

Random Array: 
 [[31  4 13 59 48]
 [98 74 77 25 57]
 [13  5 91  6 49]
 [19 26 56 81 28]
 [20 81 91 73 55]]


In [38]:
mean = X.mean() #Extract the mean of the given array
std = X.std() #Extract the standard deviation of the given array
print('\nMean: ', mean, '\nStandard Deviation: ', round(std,2))


Mean:  47.2 
Standard Deviation:  29.76


In [40]:
#Calculate for the normalized array
cent = (X-mean) #Centering is the subtraction of data from the mean
scale = cent/std #Dividing it by the std is scaling
print('\nNormalized Array: \n', scale)


Normalized Array: 
 [[-0.54432337 -1.45152899 -1.14912712  0.39648246  0.02688017]
 [ 1.70689057  0.90048558  1.0012862  -0.74592462  0.32928204]
 [-1.14912712 -1.41792878  1.47168912 -1.38432858  0.06048037]
 [-0.94752587 -0.71232441  0.29568183  1.13568704 -0.645124  ]
 [-0.91392566  1.13568704  1.47168912  0.86688537  0.26208162]]


In [42]:
np.save('X_normalized.npy', scale) #Save the normalized array in a .npy file

In [44]:
np.load('X_normalized.npy') #Load the file to check if the array is saved successfully

array([[-0.54432337, -1.45152899, -1.14912712,  0.39648246,  0.02688017],
       [ 1.70689057,  0.90048558,  1.0012862 , -0.74592462,  0.32928204],
       [-1.14912712, -1.41792878,  1.47168912, -1.38432858,  0.06048037],
       [-0.94752587, -0.71232441,  0.29568183,  1.13568704, -0.645124  ],
       [-0.91392566,  1.13568704,  1.47168912,  0.86688537,  0.26208162]])

# DIVISIBLE BY 3 PROBLEM
### This problem checks the numbers that are divisible by 3 in the set of values in an array of positive integers 

In [47]:
#Creating a 10 by 10 array with squared numbers
num = np.arange(1,101) #Generating an array with numbers from 1-100
sqnum = num**2 #Square the numbers in the array
sqnum10 = sqnum.reshape(10,10) #Reshape the array into 10 by 10 then store it in a new variable using .reshape()
print('10by10 Squared Array: \n', sqnum10)

10by10 Squared Array: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [49]:
divby3 = sqnum10[sqnum10%3 == 0] #Find all the numbers that are divisible by 3 and store it in a new variable
print('Divisible by 3 Array: \n', divby3)

Divisible by 3 Array: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [51]:
np.save('div_by_3.npy', divby3) #Save the new array in a .npy file

In [53]:
np.load('div_by_3.npy') #Load the file to check if the array is successfully saved

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])